language: cpp

matrix: 
  include: 
    - os: linux
      install: 
        - "sudo apt install make mesa-common-dev libglu1-mesa-dev"
        - ./Tools/generate_project_linux.sh
      script: make
    - os: windows
      install: 
        - "echo %cd%"
        - "call ./Tools/generate_project_win.bat -s"
      script: "msbuild PhotonBox.sln /p:Configuration=Debug"