name: C++ Builder

on: 
  push:
    branches:
    - master

jobs:
  build-win:
   runs-on: windows-latest    
   steps:
    - uses: actions/checkout@v1
    
    - name: Install
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: Generate
      run: ./Tools/generate_project_win.bat -s

    - name: Build
      run: MSBuild.exe PhotonBox.sln
      
    - name: Package
      run: ./Tools/deployer_win.bat Debug -s
      
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: ${{ runner.os }}
        path: Build/Debug
    
  build-linux:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v1
    
    - name: Install
      run: |
       sudo apt-get update
       sudo apt-get install mesa-common-dev libglu1-mesa-dev xorg-dev
      
    - name: Generate
      run: ./Tools/generate_project_linux.sh
      
    - name: Build
      run: make
      
    - name: Package
      run: sudo ./Tools/deployer_linux.sh Debug

    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: ${{ runner.os }}
        path: Build/Debug

