name: CPP Builder

on:
  push:
    branches:
      - dev
      
jobs:
  build-win:
    name: Windows Build
    runs-on: windows-latest
    steps:
      - name: Download Repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Setup Environment
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Generate Solution
        run: ./scripts/generate_project_win.bat -s
      - name: Build
        run: 'MSBuild.exe ./build/PhotonBox.sln /p:Configuration=Release'
      - name: Test
        run: ./scripts/code_checker_win.bat -s
      - name: Package
        run: ./scripts/package_win.bat -s
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: 'PhotonBox-${{ runner.os }}'
          path: |
            ./lib
            ./include
            ./pb_res
  
  build-linux:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
      - name: Download Repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Setup Environment
        run: |
          sudo chmod +x ./scripts/*.sh
          sudo apt-get update
          sudo apt-get install mesa-common-dev libglu1-mesa-dev xorg-dev
      - name: Generate Solution
        run: ./scripts/generate_project_linux.sh
      - name: Build
        run: |
          cd ./build
          sudo make config=Release
      - name: Test
        run: ./scripts/code_checker_linux.sh -s
      - name: Package
        run: ./scripts/package_linux.sh
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: 'PhotonBox-${{ runner.os }}'
          path: |
            ./lib
            ./include
            ./pb_res
  
  build-mac:
    name: Mac Build
    runs-on: macos-latest
    steps:
      - name: Download Repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Setup Environment
        run: |
          sudo chmod +x ./scripts/*.sh
      - name: Generate Solution
        run: ./scripts/generate_project_mac.sh
      - name: Build
        run: |
          cd ./build
          xcodebuild -project PhotonBox.xcodeproj -configuration Release
      - name: Test
        run: ./scripts/code_checker_mac.sh -s
      - name: Package
        run: ./scripts/package_mac.sh
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: 'PhotonBox-${{ runner.os }}'
          path: |
            ./lib
            ./include
            ./pb_res