name: C++ Builder

on: 
  push:
    branches:
    - dev

jobs:
  build-win:
   name: Windows Build
   runs-on: windows-latest
   strategy:
     matrix: 
       conf: [Debug, Release]
   steps:
    - name: Download Repository
      uses: actions/checkout@v1
    - name: Setup Environment
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Generate Solution
      run: ./Tools/generate_project_win.bat -s
    - name: Build
      run: ./Tools/build_project_win.bat ${{matrix.conf}} -s
    - name: Test
      run: ./Tools/code_checker_win.bat -s
    - name: Package
      run: ./Tools/package_win.bat ${{matrix.conf}} -s
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: PhotonBox-${{ runner.os }}-${{matrix.conf}}
        path: Build/${{matrix.conf}}
    
  build-linux:
   name: Linux Build
   runs-on: ubuntu-latest
   strategy:
     matrix: 
       conf: [Debug, Release]
   steps:
    - name: Download Repository
      uses: actions/checkout@v1
    - name: Setup Environment
      run: |
       sudo apt-get update
       sudo apt-get install mesa-common-dev libglu1-mesa-dev xorg-dev
    - name: Generate Solution
      run: ./Tools/generate_project_linux.sh
    - name: Build
      run: ./Tools/build_project_linux.sh ${{matrix.conf}}
    - name: Test
      run: ./Tools/code_checker_linux.sh -s
    - name: Package
      run: sudo ./Tools/package_linux.sh ${{matrix.conf}}
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: PhotonBox-${{ runner.os }}-${{matrix.conf}}
        path: Build/${{matrix.conf}}

#  build-mac:
#   name: Mac Build
#   runs-on: macos-latest
#    strategy:
#      matrix: 
#       conf: [Debug, Release]
#   steps:
#    - name: Download Repository
#      uses: actions/checkout@v1
#    - name: Setup Environment
#      run: 
#    - name: Generate Solution
#      run: ./Tools/generate_project_mac.sh
#    - name: Build
#      run: ./Tools/build_project_mac.sh ${{matrix.conf}}
#    - name: Test
#      run: ./Tools/code_checker_mac.sh -s
#    - name: Package
#      run: sudo ./Tools/package_linux.sh ${{matrix.conf}}
#    - name: Upload Artifact
#      uses: actions/upload-artifact@v1
#      with:
#        name: PhotonBox-${{ runner.os }}-${{matrix.conf}}
#        path: Build/${{matrix.conf}}
